apiVersion: v2
appVersion: "1.2.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
description: A Helm chart for Kubernetes
name: rabbitmq-queue-management
version: 0.2.0
